apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "kubei"
  labels:
    app.kubernetes.io/name: "kubei"
    app.kubernetes.io/version: "9.1.1"
spec:
  selector:
    matchLabels:
     app.kubernetes.io/name: "kubei"
  componentKinds: []
  descriptor:
    version: "9.1.1"
    description: "Open-source error tracking with full stacktraces & asynchronous context."
    icons:
      - src: "https://www.portshift.io/wp-content/uploads/2020/03/icon-color.png"
        type: "image/png"
    type: "kubei"
    links:
      - description: Open kubei UI
        url: "http://kubei/view:8080"