apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: kubei
  annotations:
    kots.io/when: '{{repl ConfigOptionEquals "use_ingress" "1" }}'
spec:
  rules:
  - http:
      paths:
        - path: /
          backend:
            serviceName: kubei
            servicePort: 8080