apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kots.io/when: '{{repl ConfigOptionEquals "use_ingress" "1" }}'
spec:
  rules:
  - http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: kubei
              port:
                number: 8080
