apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: "kubei"
  labels:
    app.kubernetes.io/name: "kubei"
    app.kubernetes.io/version: "0.9.0"
spec:
  title: my Kubei application 
  icon: https://www.portshift.io/wp-content/uploads/2020/03/icon-color.png
  additionalNamespaces: 
    - "*"
  statusInfromers:
    - deployment.apps/kubei
    - service/kubei

