apiVersion: kots.io/v1beta1
kind: Config
metadata:
  name: config-sample
spec:
  groups:
    - name: config options
      title: Configuration Options  
      items:
        - name: target_namespace
          title: Define specific namespaces to scan (leave empty for all)
          type: text
          default: ''
        - name: ignore_namespace
          title: Define namespaces to skip scan for (leave empty for none)
          type: text
          default: ''
        - name: explanation 
          type: label
          title: "Note: the system will scan according to the above configuration"
    - name: Optional_Components
      title: Artifactory Optional Components
      items:
        - name: distribution
          value: '{{repl Distribution}}'
          hidden: true