apiVersion: kots.io/v1beta1
kind: Config
metadata:
  name: config-sample
spec:
  groups:
    - name: config options
      title: Configuration Options  
      items:
        - name: target_namespace
          title: Define specific namespaces to scan (leave empty for all)
          type: text
          default: ''
        - name: ignore_namespace
          title: Define namespaces to skip scan for (leave empty for none)
          type: text
          default: ''
        - name: explanation 
          type: label
          title: "Note: the system will scan according to the above configuration"
        - name: proxy_enabled
          title: Connect Appliance to Proxy
          type: bool
          default: "0"
        - name: proxy_host
          title: Proxy Host
          type: text
          when: '{{repl (ConfigOptionEquals "proxy_enabled" "1")}}'
        - name: proxy_port
          title: Proxy Port
          type: text
          when: '{{repl (ConfigOptionEquals "proxy_enabled" "1")}}'
        - name: proxy_username
          title: Proxy Username
          type: text
          when: '{{repl (ConfigOptionEquals "proxy_enabled" "1")}}'
        - name: proxy_password
          title: Proxy Password
          type: password
          when: '{{repl (ConfigOptionEquals "proxy_enabled" "1")}}'
    - name: hidden options
      title: hidden items
      items:
        - name: distribution
          value: '{{repl Distribution}}'
          hidden: true
  TARGET_NAMESPACE: '{{repl ConfigOption "target_namespace" }}'
  IGNORE_NAMESPACES: '{{repl ConfigOption "ignore_namespace" }}'